### ISSUE TITLE
Instructions and scripts for building on Windows

### ISSUE THREAD

**Issue by joshgav** [AzureAD/rms-sdk-for-cpp#1]
Provide instructions and scripts for downloading includes and libs for OpenSSL and building this project on Windows. No includes or libs should be stored within the repo.

**Comment by BrucePerlerMS** [comment]
This issues need to be assigned to the engineering team for analysis and testing before it can be published.

**Comment by prvijay** [comment]
@AgentRX does this work today, should we close this issue or continue to track it?

**Comment by BrucePerlerMS** [comment]
I think this issue needs to remain open.
