### ISSUE TITLE
Get a empty folder(~)   when decrypting the files

### ISSUE THREAD

**Issue by Kammy6679** [AzureAD/rms-sdk-for-cpp#105]
RMS SDK generates a empty folder when decrypting the files, . Please see the following screenshot:

![2](https://cloud.githubusercontent.com/assets/10860444/9809758/a5531074-589d-11e5-92f6-962a64307ed2.png)

**Comment by AgentRX** [comment]
Fixed in: https://github.com/AzureAD/rms-sdk-for-cpp/pull/107
