### ISSUE TITLE
Calling "ProtectedFileStream::Acquire" or "UserPolicy::Acquire", and then close Foxit Reader. We find thant a process stays in main memory

### ISSUE THREAD

**Issue by Kammy6679** [AzureAD/rms-sdk-for-cpp#114]
Calling "ProtectedFileStream::Acquire" or "UserPolicy::Acquire", and close Foxit Reader. We find thant a process stays in main memory. This will cause that Foxit Reader can‘t be start.

Here is a video for this issue: http://sync-us.foxitsoftware.com/pm/rms/temp/BUG.wmv

**Comment by prvijay** [comment]
I have not seen any followup on this issue - is it still a problem? Can you please reactivate it if appropriate?
