### ISSUE TITLE
How to get the RMS Server address (such as:https://adrms.mobile.cn) when encrypting the files?

### ISSUE THREAD

**Issue by Kammy6679** [AzureAD/rms-sdk-for-cpp#116]
How to get the RMS Server address (such as:https://adrms.mobile.cn) when encrypting the files?

In ConsentList Consents(ConsentList& consents), we can use IConsent  to the RMS server address when decrypting the files.

In Windows, set dwPropID to IPC_LI_CONNECTION_INFO when calling 
IpcGetSerializedLicenseProperty(https://msdn.microsoft.com/en-us/library/windows/desktop/hh995038(v=vs.85).aspx), to get the RMS server address. 

Can you provide similar interfaces(IPC_LI_CONNECTION_INFO) in UserPolicy to get these information?

**Comment by Kammy6679** [comment]
Please open this issue. You don't provide any suggestion for this

**Comment by prvijay** [comment]
@Kammy6679 - Please re-open the issue (or) open a new issue. This is the only we can track effectively.

**Comment by prvijay** [comment]
@Kammy6679 - Please go through the documentation @ https://technet.microsoft.com/en-us/library/dn673574(v=ws.11).aspx#BKMK_SRV  on how to create a DNS record - that should be sufficient to address the scenario at hand (for encryption and decryption).

**Comment by Kammy6679** [comment]
@prvijay ,  We do not understand @ https://technet.microsoft.com/en-us/library/dn673574(v=ws.11).aspx#BKMK_SRV
Can you please provide a sample for how to get the Azure RMS server address and the ADFD RMS server address?

**Comment by Kammy6679** [comment]
@prvijay, any update?
