### ISSUE TITLE
AuthenticationContext.acquireToken() ignores PromptBehavior parameter

### ISSUE THREAD

**Issue by lesterpotter** [AzureAD/rms-sdk-for-cpp#117]
Delete your token cache.
Using RmsAuth_Sample, on the "authorization_code" tab, select prompt=Never.
I expect acquireToken to fail, but instead it Prompts for a password.

**Comment by raeitan** [comment]
Are you using it with a ocal ADFS ? 
or is it AADFS ?

**Comment by lesterpotter** [comment]
Azure AD

Les Potter

**Comment by raeitan** [comment]
RMSAuth was designed according to specs of oauth2 (evo) but when it goes to the cloud v1 endpoint or onprem endpoints (which is always v1) it is using our old STS which isn't a full implementation. 
That doesn’t support the flag “promt=attempt_none” 
When we move the linux SDK to evo we can update the rmsauth sample which directly access https://sts.aadrm.com to access https://sts.windows.net/ instead.
you can point the RMSAuth sample app to the sts.windows.net and it will generate a token and take the prompt paramter into account but the token wont be usu-able by the RMS SDK. The Linux RMS SDK is set up to only request authentication against the RMS STS

*This will still not work on onprem cases as the server code there isn’t expected to be updated anytime soon.

**Comment by lesterpotter** [comment]
Where can I find documentation on the "v1 endpoint / old STS"?

https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-2322-a
Virus-free.
www.avast.com
https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-2322-a
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by raeitan** [comment]
Hey, 
We currently don't have direct documentation of the RMS STS as it was meant to be an internal mechanism and is considered being a legacy. 
Is there any reason you are trying to directly accessing it ? if you have some questions about it I can direct them to the owners of that feature.

**Comment by lesterpotter** [comment]
Yes.  My interest is in contributing to the Github project.  You mentioned
OAuth2 is not fully implemented.

https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-2322-a
Virus-free.
www.avast.com
https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-2322-a
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
