### ISSUE TITLE
Cannot open the PPDF file, which is protected by RMS Android SDK

### ISSUE THREAD

**Issue by Kammy6679** [AzureAD/rms-sdk-for-cpp#119]
1. Protect a PDF file to PPDF file by RMS Android SDK
2. Open this PPDF by RMS Linux SDK
   3 Get the a error message : This version is not supported. 
3. Check the code, we found that the following functions have an exception error
   ProtectedFileStream::Acquire

PS: Please use "catch (const rmscore::exceptions::RMSException& ex)" to get the exception

@prvijay , please take look this issue. Thank you.

**Comment by prvijay** [comment]
@raeitan for investigation

**Comment by Kammy6679** [comment]
Any update?

**Comment by raeitan** [comment]
Hey, 
I've updated the SDK to support pfile version 3 in the dev branch, please have a look and see if its working for you.
I'll need to run more tests before merging into master. 
Thank you for pointing to the issue. 
Feel free to re-open the issue if it still giving you difficulties.
