### ISSUE TITLE
Add docs for public headers

### ISSUE THREAD

**Issue by joshgav** [AzureAD/rms-sdk-for-cpp#12]
Use [Doxygen](http://www.doxygen.org) [commands](http://www.stack.nl/~dimitri/doxygen/manual/commands.html).

Public surface is in header files in:
- sdk/rms_sdk/ModernAPI
- sdk/rmsauth_sdk/rmsauth/rmsauth

**Comment by joshgav** [comment]
I've added docs to [ProtectedFileStream.h](https://github.com/AzureAD/rms-sdk-for-cpp/blob/master/sdk/rms_sdk/ModernAPI/ProtectedFileStream.h) and [IAuthenticationCallback.h](https://github.com/AzureAD/rms-sdk-for-cpp/blob/master/sdk/rms_sdk/ModernAPI/IAuthenticationCallback.h) which can serve as examples on formatting for more.

All doc comment commands can be found in the [Commands](http://www.stack.nl/~dimitri/doxygen/manual/commands.html) section of the Doxygen manual.

@BrucePerlerMS @prvijay

**Comment by BrucePerlerMS** [comment]
Ok. Now that I'm back from vacation I can dig into these.
@joshgav @prvijay

**Comment by BrucePerlerMS** [comment]
This issue looks like it can be closed as its just a work item tracking issue for build the API ref, which is now complete.

**Comment by prvijay** [comment]
Ok closing it,
