### ISSUE TITLE
Headless authorization failing

### ISSUE THREAD

**Issue by ghost** [AzureAD/rms-sdk-for-cpp#123]
I am trying to set up an app using non-interactive authentication. I can authorize against https://login.microsoftonline.com/tenant.onmicrosoft.com/oauth2/token using either client credentials or user credentials. However, upon trying to actually use the token which is returned I get a 401 response with the message "The authorization token is not well-formed". 

Is this a case of me using the wrong authority or a problem with the token which is returned? https://jwt.io/ says that the token has an invalid signature.

**Comment by raeitan** [comment]
Hey,
We currently do not support the general authorization endpoints (aka EVO), we have our own STS. 
When consuming, the callback will provide the authorization URL that should be used to generate the token. 
Support for the EVO authorization is available in the other platforms and is coming to the Linux one as well.

**Comment by ghost** [comment]
Hey, thanks for that. Does that STS support client credential authentication? Whenever I try to use the client_credentials grant type I get an "unsupported grant type" error.

Thanks

**Comment by gaurav17281** [comment]
@jasonsgordon I'm trying something similar. Can you please share what are the various parameters that are being used. I'm looking for the information/documentation on the following - 
- Resource - I'm assuming this is the target resource that the client wants to access. But what is the format for this. Can it be a remote/local resource?
-  client_secret - Who assigns/generate the client secret? I don't see this on azure portal at all. 
- Authority - It appears that this is the parameter from your Application configuration on Azure?

Can you please help identifying this information?

Thanks,
- G

**Comment by ghost** [comment]
I have been using:
  Resource -> api.aadrm.com
  Client_Secret -> You get this from your apps registration page in Azure Portal
  Authority -> Not sure what the correct one is, hence this issue.

Hope that helps.
