### ISSUE TITLE
Log full request/response in debug

### ISSUE THREAD

**Issue by joshgav** [AzureAD/rms-sdk-for-cpp#13]
In debug build, log entire HTTP request and response.

**Comment by AgentRX** [comment]
@joshgav, actually all requests and responses are already been logging into *.log files

**Comment by AgentRX** [comment]
@joshgav, to find logging implementation you can view HttpClientQt.cpp file

**Comment by AgentRX** [comment]
Also I fixed small bug - writng vector into log without convertion to string (without null terminated character).
https://github.com/AzureAD/rms-sdk-for-cpp/pull/18

**Comment by joshgav** [comment]
thanks! will try this now.

**Comment by joshgav** [comment]
@AgentRX, can we log the headers from requests too?

**Comment by AgentRX** [comment]
Added by https://github.com/AzureAD/rms-sdk-for-cpp/pull/21

**Comment by joshgav** [comment]
This is great! Merging now. As discussed offline, let's enable Debug logging in non-debug builds as well, and make it depend on an environment variable. I propose `RMS_DEBUG` as the variable and if it's set to anything other than `0` or `false` to log debug messages too.

**Comment by joshgav** [comment]
Will close this, thanks @AgentRX, and use #27 for `Logger::hidden()`
