### ISSUE TITLE
Policy name and description not persisted through unprotection

### ISSUE THREAD

**Issue by joshgav** [AzureAD/rms-sdk-for-cpp#15]
From @Kammy6679 

We are using a custom (ad hoc) policy to protect a file and set policy name and description. At unprotection time, the policy name and description are changed to “Restricted Access” and “Permission is currently restricted. Only specified users can access this content.”

Here is our code.

```
bool CMSDataInteractionLinux::InitMSProtectedDataWithFilePath(FS_LPCWSTR lpwsFilePath)
{
    m_qsfilePath = QString::fromWCharArray((wchar_t *)lpwsFilePath);
    QString qsUser;
    theApp.GetLoggingAccessToken(qsUser);
    m_orgFile.setFileName(m_qsfilePath);
    if (!m_orgFile.open(QIODevice::ReadOnly))
    {
        return false;
    }
    m_bNeedCloseOrgFile = true;

    QSharedPointer<QDataStream> orgFileStream = QSharedPointer<QDataStream>::create(&m_orgFile);
    SharedStream orgIStream = QTStreamImpl::Create(orgFileStream);
    std::string userId = qsUser.toStdString();
    addCertificates();
    m_protectedFileStreamResult = ProtectedFileStream::Acquire(orgIStream,
                                                 userId,
                                                 m_authenticationCallback,
                                                 m_consentCallback,
                                                 POL_None);

    if ((m_protectedFileStreamResult.get() != nullptr) &&
        (m_protectedFileStreamResult->m_status == Success) &&
        (m_protectedFileStreamResult->m_stream != nullptr))
    {
        bool bCanRead = m_protectedFileStreamResult->m_stream->CanRead();
        if (!bCanRead)
            return false;
        m_dwDocSize = m_protectedFileStreamResult->m_stream->Size();
        m_bCusProtectedFile = false;
        m_pUserPolicy = m_protectedFileStreamResult->m_stream->Policy();
        return true;
    }

    return false;
}
```

**Comment by AgentRX** [comment]
Hello, @munjaldoshi 

Something strange with this.

**Here is request to Azure EP of creating ProtectionPolicy:**
`{"AllowAuditedExtraction":true,"Descriptors":[{"Description":"TestDescPolicy","Language":"en_US","Name":"TestNamePolicy"}],"Policy":{"LicenseValidUntil":"Fri Jun 24 18:02:58 2016","UserRights":[{"Rights":["OWNER","VIEW","EDIT","EXPORT","EXTRACT"],"Users":["v-anpogo@microsoft.com"]}],"allowOfflineAccess":true},"PreferDeprecatedAlgorithms":false,"ReferralInfo":"https://client.test.app"}`

**And here is UsageRestrictionsResponse from it:**
`{"Id":"00000000-0000-0000-0000-000000000000","Name":"Restricted Access","Description":"Permission is currently restricted. Only specified users can access this content.","Referrer":"https://client.test.app/","Owner":"john.smith@msopentechtest01.onmicrosoft.com","AccessStatus":"AccessGranted","Key":{"Value":"m/pi2v5X2dmFih7XkaVbkg==","CipherMode":"MICROSOFT.CBC4K","Algorithm":"AES"},"Rights":["OWNER","AUDITEDEXTRACT"],"Roles":null,"IssuedTo":"john.smith@msopentechtest01.onmicrosoft.com","ContentValidUntil":null,"LicenseValidUntil":"2015-07-25T15:05:07Z","ContentId":"eb91da0f-a6cf-4b9e-acbd-ba1741ad6fed","SignedApplicationData":null,"EncryptedApplicationData":null,"FromTemplate":false,"Policy":{"AllowAuditedExtraction":true,"UserRights":[{"Users":["v-anpogo@microsoft.com"],"Rights":["OWNER","VIEW","EDIT","EXPORT","EXTRACT"]}],"UserRoles":null,"IntervalTimeInDays":30,"LicenseValidUntil":null}}`

As you can see, name and description were changed. What should we do to fix it?

**Comment by joshgav** [comment]
@gurgenh

**Comment by vladimp** [comment]
Hi Andrey,

The "Descriptors" object is in a wrong place.
When creating the protection policy the "Descriptors" object should be inside the "Policy" dictionary.
For example:

```
{
    AllowAuditedExtraction = 0;
    Policy =     {
        Descriptors =         (
                        {
                Description = "Adhoc Policy Description";
                Language = "en-us";
                Name = "Adhoc Policy";
            }
        );
        UserRights =         (
                        {
                Rights =                 (
                    VIEW,
                    DOCEDIT,
                    EDIT,
                    EXTRACT,
                    PRINT,
                    OBJMODEL,
                    OWNER,
                    EXPORT
                );
                Users =                 (
                    "alice@isvtenant998.onmicrosoft.com"
                );
            },
                        {
                Rights =                 (
                    VIEW,
                    OBJMODEL
                );
                Users =                 (
                    ANYONE
                );
            }
        );
    };
    PreferDeprecatedAlgorithms = 1;
}
```

Please let me know if you have any further issues.

Vladi.

**Comment by joshgav** [comment]
Re-opening till we implement this fix. @AgentRX please work on this. Thanks!

**Comment by AgentRX** [comment]
Hi @vladimp,

Unfoirtinately it haven't helped. I used this request:

```
{  
   "AllowAuditedExtraction":true,
   "Policy":{  
      "Descriptors":[  
         {  
            "Description":"Test description",
            "Language":"en_US",
            "Name":"Test name"
         }
      ],
      "LicenseValidUntil":"Sat Jun 25 13:13:22 2016",
      "UserRights":[  
         {  
            "Rights":[  
               "OWNER",
               "VIEW",
               "EDIT",
               "EXPORT",
               "EXTRACT"
            ],
            "Users":[  
               "v-anpogo@microsoft.com"
            ]
         }
      ],
      "allowOfflineAccess":true
   },
   "PreferDeprecatedAlgorithms":false,
   "ReferralInfo":"https://client.test.app"
}
```

and got response BAD REQUEST with message "Parameter Invalid Descriptor is invalid."
Also I tried use 'Descriptorts' like an object:

```
 "Descriptors": {  
            "Description":"Test description",
            "Language":"en_US",
            "Name":"Test name"
         }
```

It also doesn't work.

We took JSON serializer from RMS Windows SDK and there is the same PublishCustomRequest format (Descriptors goes at the same level with Policy, not inside it)

**Comment by AgentRX** [comment]
Fixed

**Comment by joshgav** [comment]
Thanks @AgentRX!
