### ISSUE TITLE
Add ProtectedFileStream::WriteAsync()

### ISSUE THREAD

**Issue by joshgav** [AzureAD/rms-sdk-for-cpp#2]
`ReadAsync()` is currently available but not `WriteAsync()`. WriteAsync() wasn't added because writes aren't thread-safe. After discussion, we decided we should still provide a non-thread-safe WriteAsync() which sets up a worker thread calling `Write()`. It is understood that only one thread at a time should be working with one target stream and that neither `Write()` nor `WriteAsync()` is thread-safe.

**Comment by AgentRX** [comment]
Done by https://github.com/AzureAD/rms-sdk-for-cpp/pull/26

**Comment by joshgav** [comment]
Thanks!
