### ISSUE TITLE
Add logic for distro detection to qmake files

### ISSUE THREAD

**Issue by joshgav** [AzureAD/rms-sdk-for-cpp#22]
As discussed in #19, the qmake (.pro) files need to branch based on distro for some things such as install target (CentOS and OpenSUSE use `/usr/lib64` and Ubuntu uses `/usr/lib/x86_64-linux-gnu`).

We should put this shared logic in a separate file and include it in .pro files through an [`include()`](http://doc.qt.io/qt-5/qmake-test-function-reference.html#include-filename) statement.

**Comment by AgentRX** [comment]
Should be done by any Linux systems developer or administrator

**Comment by prvijay** [comment]
@AgentRX - so what is the next step? Should the issue still be left open?

**Comment by AgentRX** [comment]
@prvijay, it's not actual at now
