### ISSUE TITLE
Automate build/test on multiple platforms

### ISSUE THREAD

**Issue by joshgav** [AzureAD/rms-sdk-for-cpp#23]
Building on #10, see if we can use Docker to build/test on multiple target platforms from Travis or other CI systems.

**Comment by AgentRX** [comment]
Should be done by Travis systems administrator

**Comment by prvijay** [comment]
@AgentRX - what is the next step? Why is it still open?

**Comment by AgentRX** [comment]
@prvijay, it's not actual at now
