### ISSUE TITLE
Add Logger::hidden to rms_sdk

### ISSUE THREAD

**Issue by joshgav** [AzureAD/rms-sdk-for-cpp#27]
`Logger::hidden()` was added to rmsauth_sdk in #25 to ensure that by default sensitive data is not stored in logs but still allow it to be enabled with an environment variable. A similar method should be added to rms_sdk and rmscrypto_sdk.

Afterwards, some logging should perhaps be moved from `Logger::debug()` to `Logger::hidden()` or `Logger::info()` so that it doesn't require a special debug build.

**Comment by AgentRX** [comment]
Done by https://github.com/AzureAD/rms-sdk-for-cpp/pull/36
