### ISSUE TITLE
User ID as username in logon. 

### ISSUE THREAD

**Issue by Kammy6679** [AzureAD/rms-sdk-for-cpp#29]
When `TemplateDescriptor::GetTemplateList(csUserID, m_authenticationCallback)` is called, value provided as csUserID should be used in "Username" field of logon screen.

**Comment by AgentRX** [comment]
I've added support for username as the last param of AuthenticationContext::acquireToken

It will be passed as OptionalDisplayableId for Auth2 authentication.

Also I had to remove displayId from cache key(with this key word cache had stopped to work). It's strange we used it as a key. I haven't found the same way using in AALClient.Native. So now composite key  is: { authority, resource, clientId, uniqueId }

**Comment by joshgav** [comment]
Thanks! @v-vlshch note the changed cache key, let us know if you have an issue with this.
