### ISSUE TITLE
ERROR: UsageRestrictionsClient: Got an invalid json from the REST service.

### ISSUE THREAD

**Issue by Kammy6679** [AzureAD/rms-sdk-for-cpp#35]
We are using a custom policy(On premise) to protect a file.  At unprotection time, get the error message: UsageRestrictionsClient: Got an invalid json from the REST service. You can use the sample of RMS SDK for Linux to reproduce this issue.

**Comment by AgentRX** [comment]
@Kammy6679, Could you specify custom settings you had set for the policy?

**Comment by joshgav** [comment]
And share debug logs. Instructions for doing so with latest commits is available in main README.

**Comment by Kammy6679** [comment]
Here is the setting in the sample. We get the error message when clicking "Decrypt PFILE"

![setting](https://cloud.githubusercontent.com/assets/10860444/8586429/cce7c332-2620-11e5-86a6-2fb0b1a19de3.png)

![decryption](https://cloud.githubusercontent.com/assets/10860444/8586451/020d5270-2621-11e5-8e72-17fee3379d21.png)

I will send the log files to you

**Comment by joshgav** [comment]
Confirming that I had the same issue when using ADFS/OnPrem. The JSON response itself in the hidden logs looks fine, so may be something in `JsonSerializer::DeserializeUsageRestrictionsResponse`.

It seems that `IntervalTimeInDays: null` is interpreted as a string instead of a null number, leading to an exception.

**Comment by joshgav** [comment]
Thanks @AgentRX. Are there other GetNamed\* methods in JsonSerializer where this could happen?

**Comment by AgentRX** [comment]
Also fixed GetNamedBool method.
All fixed by https://github.com/AzureAD/rms-sdk-for-cpp/pull/40

**Comment by joshgav** [comment]
Verified fixed. Thanks @AgentRX!
