### ISSUE TITLE
ProtectionPolicy::Acquire uses exceptions to handle cache miss

### ISSUE THREAD

**Issue by joshgav** [AzureAD/rms-sdk-for-cpp#37]
In ProtectionPolicy.cpp (sdk/rms_sdk/Core/ProtectionPolicy.cpp), lines 98ff., we use try/catch to check for cached responses and call the API on a cache miss. Would this be better implemented by checking if the cached entry is null or expired, rather than relying on exceptions?

**Comment by AgentRX** [comment]
Speaking about this case it doesn't matter how we signal out of cache element.

But if we're going to extend out functional (for example add some arguments checking with throwing exceptions) it's better to use exceptions.

I'm not sure we're going to change methods at nearest future. So should I change this to work without exceptions?

**Comment by joshgav** [comment]
I defer to you - if you think this arrangement is fine let's stick with it. Thanks!
