### ISSUE TITLE
Do we need to build RMS SDK for each Linux OS?

### ISSUE THREAD

**Issue by Kammy6679** [AzureAD/rms-sdk-for-cpp#42]
Do we need to build RMS SDK for each Linux OS?

**Comment by Kammy6679** [comment]
Is there any update?

**Comment by joshgav** [comment]
Hi @Kammy6679, what is the echo Linux OS? We are supporting the RMS SDK on SUSE, CentOS/RedHat, and Ubuntu.

**Comment by joshgav** [comment]
@AgentRX clarified that you meant "each" Linux distro, and I fixed the title. That's an interesting question and @AgentRX is looking into it.

**Comment by Kammy6679** [comment]
Sorry for my mistake. Yes, I mean  "each" Linux distro.

**Comment by AgentRX** [comment]
Hello @Kammy6679 ,
All Linux OS has Executable and Linkable Format (ELF) of exutables files.

#### The first condition cross-linux compartible is **target architecture**

To determine target architecture of your gcc run this command:

```
gcc -v
```

 Then find **Target:...** string. For example:

```
Target: x86_64-linux-gnu
```

That means compliled RMS library will work on the same Linux architecture.

To determine your Linux architecture just run command:

```
uname -m
```

#### The second compartible condition is supporting instruction set.

If **gcc -v** shows GCC was configured with a **--with-arch** option (or --with-arch-32 and/or --with-arch-64) then that's what will be the default instruction set. For example:

```
--with-arch-32=i686
```

##### If these both conditions are fullfilled compiled RMS libraries will work on other compartible Linux systems.

**Comment by joshgav** [comment]
Thanks @AgentRX!

**Comment by Kammy6679** [comment]
Hi AgentRX，

For each Linux OS, we follow this page(https://github.com/AzureAD/rms-sdk-for-cpp/blob/master/docs/how_to_build_it.md) to use the QT to build the RMS SDK, not use the gcc to build it.

**Comment by AgentRX** [comment]
Hi @Kammy6679,
QT uses GCC for building.
