### ISSUE TITLE
We can't set the license expiration in the custom policy

### ISSUE THREAD

**Issue by Kammy6679** [AzureAD/rms-sdk-for-cpp#43]
We can't set the license expiration in the custom policy.

**Comment by AgentRX** [comment]
@Kammy6679, there was time converting error which has been fixed in https://github.com/AzureAD/rms-sdk-for-cpp/pull/45 PR.

To set expiration time please use ContentValidUntil method of PolicyDescriptor. It will work now.

**Comment by Kammy6679** [comment]
We can use ContentValidUntil method to set the content expiration. But this is not what we want. 

We want to use OfflineCacheLifetimeInDays method(it is a method in RMS SDK for OS X) to set the license expiration.

**Comment by AgentRX** [comment]
@Kammy6679, @gurgenh wrote here: https://github.com/AzureAD/rms-sdk-for-cpp/issues/5:

> OfflineCacheLifetimeInDays should be replaced by a boolean (OfflineAccess). The app should set whether caching is allowed or not, but it shouldn't specify or make any assumptions about the longevity of the cache.

So, now it's transformed to AllowOfflineAccess boolean variable.

Please don't close the issue. I will discuss about it one more time.

**Comment by joshgav** [comment]
@Kammy6679, as @AgentRX noted `OfflineCacheLifetimeInDays` is no longer recommended. We recommend `AllowOfflineAccess` first, and `ContentValidUntil` second.

**Comment by joshgav** [comment]
If there are further questions on this please put them in #5.
