### ISSUE TITLE
Cannot open PFILE-formatted file created by Linux SDK with Windows SDK

### ISSUE THREAD

**Issue by Kammy6679** [AzureAD/rms-sdk-for-cpp#44]
1. Create an office template in ADFS/on-premise, set the content expiration and the full control permission for User A.
2.  In Ubuntu 15.04, User B uses this template to encrypt two PDF files(One is a PDF file, another is a PPDF file).
3. After the content expired:
   a. In Windows, both of User A and User B can open the protected PDF file. But we cannot get the policy name and description.
   ![1](https://cloud.githubusercontent.com/assets/10860444/8623825/4c45f8ce-2766-11e5-835f-f7c0c1ec48d6.png)
   ![2](https://cloud.githubusercontent.com/assets/10860444/8623833/5068756c-2766-11e5-82b1-1c81d2251641.jpg)
   b. In Windows, both of User A and User B cannot open the protected PPDF file, but get the following error message.
   ![123123213213](https://cloud.githubusercontent.com/assets/10860444/9102476/4f11140c-3c25-11e5-8a94-66f66178ab8a.jpg)

PS:
In Linux, both of User A and User B can open the protected PDF file and PPDF file, and get the policy name and description.

**Comment by joshgav** [comment]
@gurgenh Please review how the Windows SDK interprets name/desc information from consumption response. There may be an issue there, see #15.

@vladimp Is content expiry as described here the expected behavior?

@Kammy6679 What is the difference between PPDF and PDF in this case - just the extension?

**Comment by vladimp** [comment]
No, it is not the expected you should get No rights error from the server when the content expired..
Please remove your cache and try to run the scenario again.
(The name/desc on windows is probably a known issue..)

**Comment by Kammy6679** [comment]
@joshgav PPDF is a Microsoft RMS protected format. You don't know it？？？？

we use the follow method to encrypt a PDF file to PPDF/PDF：

PPDF: `std::shared_ptr<ProtectedFileStream>`
PDF: `std::shared_ptr<CustomProtectedStream>`

**Comment by Kammy6679** [comment]
any update?

**Comment by joshgav** [comment]
@Kammy6679 `ProtectedFileStream` represents the PFILE format and `CustomProtectedStream` is non-PFILE format. So it seems you aren't able to open a PFILE-formatted file in the Windows SDK when created by the Linux SDK. I'll ask the Windows SDK team to provide more guidance.

/cc @prvijay @gurgenh

**Comment by AgentRX** [comment]
Reproduced only on a source file without extension on Azure
Will be checked on onPrem.

**Comment by AgentRX** [comment]
Linked with https://github.com/AzureAD/rms-sdk-for-cpp/issues/73
Azure doesn't return Protection Policy for expired content. So now RMS will return expired state and nullptr protected stream

**Comment by prvijay** [comment]
Johnny, can you validate and comment on the issue?

**Comment by Kammy6679** [comment]
This issue has been fixed. But #73 still exists

**Comment by prvijay** [comment]
On behalf of Johnny - issue has been fixed and hence closing the bug
