### ISSUE TITLE
Process to manually test rmsauth

### ISSUE THREAD

**Issue by joshgav** [AzureAD/rms-sdk-for-cpp#46]
We don't yet have secrets encrypted for use with Travis tests. Can we please document how to manually test the rmsauth library on a dev machine with local credentials?

**Comment by AgentRX** [comment]
Hello @joshgav,

Should I create documentation for both UI/noneUI testing?

**Comment by joshgav** [comment]
Yes, that would be great. Thanks!

**Comment by AgentRX** [comment]
1. Copy all .so compiled libraries to /usr/lib
2. Run from bin/tests/rmsauthUnitTests --cl <clientId> --r <resource> --a <authority> --u <userName> --p <password> -cp <certificatesPath>

It's strange but password for john.smith@msopentechtest01.onmicrosoft.com doen't work now and I can't test it.

**Comment by joshgav** [comment]
Got a couple failures, can you try with the newly-reset password?
Also, any ideas on how to suppress (or address?) the SSL warnings?
Thanks!

**Comment by AgentRX** [comment]
Should be fixed if it's still necessary to test it manually.

**Comment by prvijay** [comment]
@AgentRX - can we close it?

**Comment by AgentRX** [comment]
@prvijay, I think so. Issue is not necessary at now.
