### ISSUE TITLE
how to specify the certificate path

### ISSUE THREAD

**Issue by Kammy6679** [AzureAD/rms-sdk-for-cpp#49]
Using on-premise RMS server/ADFS, we use the following code(the same with your sample code) to specify a certificate path. But if the user install the certificate by himself, we cannot get the certificate. In this case, how to specify the certificate path?
![123](https://cloud.githubusercontent.com/assets/10860444/8717835/7ca1bd2c-2bd1-11e5-8b8c-053818d48eea.png)

**Comment by AgentRX** [comment]
Hi @Kammy6679 
You can add certificates from standard paths:

```
/etc/ssl/certs
/etc/ssl/private (chmod 700)
```

**Comment by joshgav** [comment]
Also, if the certificate is in a trusted store on the user's system I believe. More details on adding CA certs for Ubuntu [here](http://superuser.com/questions/437330/how-do-you-add-a-certificate-authority-ca-to-ubuntu).

**Comment by Kammy6679** [comment]
@AgentRX 

Using the following code cannot find the certifications:
QString qsCertificatesDir = "/etc/ssl/private";
QString qsCertificatesDir = "/etc/ssl/certs";

In OS X or Windows, RMS SDK can automatically find the relevant certificates. Can RMS SDK for Linux aslo do this by itself, not use the following code(the same with your sample code) ？

![123](https://cloud.githubusercontent.com/assets/10860444/8741847/4a5b0da8-2c91-11e5-947f-46b1739d4c37.png)

**Comment by Kammy6679** [comment]
Any update？

**Comment by AgentRX** [comment]
@Kammy6679, it works on Ubuntu. What OS do you use?
Please check if /etc/ssl path exists in your system?

**Comment by Kammy6679** [comment]
We are using Ubuntu 14.10, and /etc/ssl path exists in my system. But can't find the certifications from standard paths:
/etc/ssl/certs
/etc/ssl/private (chmod 700)

**Comment by Kammy6679** [comment]
any update?

**Comment by AgentRX** [comment]
@Kammy6679, please change the above function code at line 20 to:

```
QDir dir("/etc/ssl/certs");
```

Will it work? I've just tested and it founded certificates.

**Comment by Kammy6679** [comment]
We still can’t find the certificate in "/etc/ssl/certs" in ubuntu14.10 ,opensuse 13.2  and red hat 7.0

PS: we use “import” to install the certificate.
![123](https://cloud.githubusercontent.com/assets/10860444/9242379/fa65987c-41b2-11e5-91dd-b3ac22f69ce1.jpg)

**Comment by AgentRX** [comment]
@Kammy6679, when you install certificate by importing it will be pushed to you key ring storage.

I don't know how to get the certificate from storage but if you can do it just call HttpHelper::addCACertificateDer of HttpHelper::addCACertificateBase64 to add it as trusted for RMS/ADAL libraries.

Here is official Ubuntu site: https://help.ubuntu.com/lts/serverguide/certificates-and-security.html
They write:

```
Installing the Certificate
You can install the key file server.key and certificate file server.crt, or the certificate file issued by your CA, by running following commands at a terminal prompt:

sudo cp server.crt /etc/ssl/certs
sudo cp server.key /etc/ssl/private
Now simply configure any applications, with the ability to use public-key cryptography, to use the certificate and key files. For example, Apache can provide HTTPS, Dovecot can provide IMAPS and POP3S, etc.
```

I think you can do the same way in other OSes.
