### ISSUE TITLE
Host API docs in GitHub Pages

### ISSUE THREAD

**Issue by joshgav** [AzureAD/rms-sdk-for-cpp#51]
@BrucePerlerMS @prvijay

**Comment by BrucePerlerMS** [comment]
Given our conversations to date and the direction our teams are going with Azure documentation, yes it seems that anything that works and fits the audience space is fair game. So, I agree that hosting the API ref on Git is a fine approach. 

@joshgav

**Comment by BrucePerlerMS** [comment]
This issue can be closed now since the API ref has been built and posted to GitHub.io
