### ISSUE TITLE
Compiling on RedHat 6.5

### ISSUE THREAD

**Issue by Kammy6679** [AzureAD/rms-sdk-for-cpp#52]
Please provide the both the operating system name and the version.

**Comment by joshgav** [comment]
This information is available on [this page](https://github.com/AzureAD/rms-sdk-for-cpp/blob/master/docs/how_to_build_it.md).

**Comment by Kammy6679** [comment]
Do you mean the RMS SDK for Linux just supported:
Ubuntu 14.04
Open SUSE 13.2
Red hat 7

Here’s the information requested(from Intel):
Red Hat 6 & 7
SUSE 12 & 13 
Ubuntu 12, 14 and 15

Do you have any suggestion?

**Comment by joshgav** [comment]
The OS's listed are where we've done complete testing. You're free to run/test on other OS's and submit issues for fixes if needed, but we can't guarantee if/when those fixes will be made. We'll also review your own code submissions. I believe we've tested (unofficially) on Ubuntu 12.04, 15.04, and OSX as well as the others listed.

Thanks!

**Comment by Kammy6679** [comment]
RMS SDK can't be used in Red hat 6.5

There are two case:
1. Build the RMS SDK in ubuntu 14.10. Then use this RMS SDK to build the app in Red hat 6.5, get the following error message:
![1](https://cloud.githubusercontent.com/assets/10860444/8794916/b0afae16-2fba-11e5-8a3e-c595b6e30b74.jpg)
1. Build the RMS SDK in Red hat 6.5 directly, we get the following error message:
   ![2](https://cloud.githubusercontent.com/assets/10860444/8794922/bba89936-2fba-11e5-8db9-22038ba7539c.jpg)

**Comment by AgentRX** [comment]
@Kammy6679, please update your GCC. The necessary version is 4.7 or above.
The reason of compilation errors is not supported c++11 on your GCC version.

**Comment by Kammy6679** [comment]
We cannot run the app in Red Hat 6.5 or other OS(Which is not include on https://github.com/AzureAD/rms-sdk-for-cpp/blob/master/docs/how_to_build_it.md ), get the following error message:
![qq 20150727111727](https://cloud.githubusercontent.com/assets/10860444/8898059/185cfa74-3451-11e5-96a1-7e0ea92c1e71.jpg)

In this case, do we need to update the C/C++ library when using the RMS feature?

**Comment by joshgav** [comment]
Please try running `sudo apt-get install libstdc++6`.

Also, is `/lib64` the correct path to `libstdc++.so.6`? You may need to adjust path-related variables. More details [here](https://www.google.com/search?q=libstdc%2B%2B.so.6+version+GLIBCXX_3.4.20+not+found).

**Comment by munjaldoshi** [comment]
Looking at the comments above, it looksl ike you need to use C++11 compatible compiler to compile the code.

**Comment by Kammy6679** [comment]
Using C++ 11 compatible compiler to compile the code, but still get the following error message:
![1233333333](https://cloud.githubusercontent.com/assets/10860444/9083451/e80bf2fa-3b9c-11e5-94e6-ba0fcf68e2ab.jpg)

**Comment by AgentRX** [comment]
@Kammy6679, please try to fix the way described here: http://stackoverflow.com/questions/1952146/glibcxx-3-4-9-not-found

**Comment by Kammy6679** [comment]
We will try this way. 

But It's not usually a good idea to replace the system compiler, because the entire system will have been built with it and depend on it. Can you please provide a new build of RMS SDK, which can be run in these OS directly?

**Comment by AgentRX** [comment]
@Kammy6679, it's possible to use several compilers versions at the same time in Linux. And RMS Library depenends on compiler's libs the version GCC was compiled with.

So it's normal situation on Linux. Also very often the same OSes has different compilers environment due to installed software dependent on compiled GCC libs versions.

**Comment by Kammy6679** [comment]
1. Upgrade "libstdc++" to 3.15
2. We find that the libc library version is too low.
3. Download glibc-2.14.tar.xz from http://ftp.gnu.org/gnu/glibc/, then compile it.
   
   a. unzip glibc-2.14.tar.xz
   b. Enter "glibc-2.14"
   c. Create a new floder "build(mkdir　build)"
   d. Run "../configure --prefix=/opt/glibc-2.14" in build folder
   d. run "make -j4"
   e. run "sudo make install"
   f. set the environment variable(/opt/glibc-2.14/lib)
4. Run Foxit reader
5. Get the error:Segmentation fault      (core dumped)

Is the process right? If not, how to upgrade glibc?

**Comment by AgentRX** [comment]
@Kammy6679, According to documentation "The current GNU C library provides the run-time **backward compatibility**"

So it means you can install higher version of GCC:
$ sudo yum install gcc
$ sudo yum update gcc

This will install the latest version of gcc and libraries. Then you can check versions by commands:
$ ldd --version
$ /sbin/ldconfig -p | grep stdc++

To deteminate supported versions use command:
strings /usr/lib/libstdc++.so.6 | grep LIBCXX
OR
strings /usr/lib64/libstdc++.so.6 | grep LIBCXX

**Comment by Kammy6679** [comment]
@AgentRX 
1. We have upgraded libstdc++.so.6
2. The problem is that libc.so.6 version is too low.
3. Use your provide method to upgrade gcc, but can not upgrade libc.so.6

**Comment by AgentRX** [comment]
Should install RedHat 6.5, build on it and update build instructions

**Comment by prvijay** [comment]
@AgentRX - can you please update the documentation to reflect this (if not done already), and close the issue? Thanks

**Comment by AgentRX** [comment]
@prvijay , I installed RedHat 6.5 to test it. Should I make minimal requirements higher instead of testing and close the issue or test it tomorrow?

**Comment by prvijay** [comment]
@AgentRX  - bump up the minimum requirement, update the document and close the issue.

**Comment by Kammy6679** [comment]
@AgentRX , How to get the update build instructions?
