### ISSUE TITLE
Add an ability to turn logs off

### ISSUE THREAD

**Issue by AgentRX** [AzureAD/rms-sdk-for-cpp#54]
Now there is no possibility to turn logs off in both RMS and ADAL SDKs.

**Comment by AgentRX** [comment]
Done by PR: https://github.com/AzureAD/rms-sdk-for-cpp/pull/81

**Comment by Kammy6679** [comment]
@AgentRX , How to turn logs off?

**Comment by AgentRX** [comment]
@Kammy6679, here is example from RMS Samples **main.cpp**:
  // set RMS Environment
  auto envRMS = rmscore::modernapi::RMSEnvironment();
  auto envAuth = rmsauth::RMSAuthEnvironment();
  envRMS->LogOption(rmscore::modernapi::IRMSEnvironment::LoggerOption::**Never**);
  envAuth->LogOption(rmsauth::IRMSAuthEnvironment::LoggerOption::**Never**);
