### ISSUE TITLE
Name and description not parsed by Windows SDK

### ISSUE THREAD

**Issue by joshgav** [AzureAD/rms-sdk-for-cpp#60]
Forked from #44.

A name and description are set for an ad-hoc policy in the Linux SDK, and when this policy is used for consumption on Linux the name and description are accurately shown. But on Windows, name and description are not shown. This may be a known issue as discussed in #44.

**Comment by prvijay** [comment]
Johnny, can you please validate if the issue has been fixed. The issue was fixed as part of the following pull request (https://github.com/AzureAD/rms-sdk-for-cpp/pull/74) which was merged to the master branch

**Comment by Kammy6679** [comment]
Thank you. It has been fixed.
