### ISSUE TITLE
Show the yellow dot

### ISSUE THREAD

**Issue by Kammy6679** [AzureAD/rms-sdk-for-cpp#61]
please see the screenshot
![qq 20150728175358](https://cloud.githubusercontent.com/assets/10860444/8930180/3c033912-355e-11e5-8092-39f476edbd1e.jpg)

**Comment by vladimir-shcherbakov** [comment]
@Kammy6679 
Could please provide steps to reproduce?

**Comment by Kammy6679** [comment]
When you log in, the dialog box will pop up. you will see the the yellow dot in the dialog.

**Comment by vladimir-shcherbakov** [comment]
Could you please provide more details?
what OS do you use?
what gcc version do you use? 
what qt version do you use?
did you build source code from master or dev branch?

**Comment by Kammy6679** [comment]
@v-vlshch , This is my bug, not RMS SDK. Thank you for your help. please close this issue
