### ISSUE TITLE
a lots of log files in drive

### ISSUE THREAD

**Issue by Kammy6679** [AzureAD/rms-sdk-for-cpp#62]
When using the RMS features in Linux, RMS SDK will generate many log files. 

![qq 20150728192652](https://cloud.githubusercontent.com/assets/10860444/8930219/a7e87142-355e-11e5-9e77-4b50d2489382.png)

**Comment by joshgav** [comment]
Hi @Kammy6679 - Can you clarify your request? Do you want to be able to disable all logging? Do you want all logs concatentated into one file?

cmp #54
//cc @prvijay

**Comment by Kammy6679** [comment]
We want to add an ability to turn logs off.

**Comment by AgentRX** [comment]
Closed due to duplicate: https://github.com/AzureAD/rms-sdk-for-cpp/issues/54
