### ISSUE TITLE
Get "Server Error" in OpenSuSe 13.2

### ISSUE THREAD

**Issue by Kammy6679** [AzureAD/rms-sdk-for-cpp#63]
Call the following method, we get "Server Error" in OpenSuSe 13.2
static std::vector<TemplateDescriptor>GetTemplateList(
    const std::string      & userId,
IAuthenticationCallback& authenticationCallback);

We have confirmed that the network connection is connected.

Here is the OS information:
![os](https://cloud.githubusercontent.com/assets/10860444/8956470/dbdc6402-3628-11e5-9f45-4fc3c550519c.png)

Here are the log files:

rms_log_010705-2907.log:
01:07:05 INF: +RestClientCache::Lookup: cacheName="msopentechtest01.onmicrosoft.com", tag="END_USER_LICENSES_UR"
01:07:05 INF: -RestClientCache::Lookup: cacheName="msopentechtest01.onmicrosoft.com", tag="END_USER_LICENSES_UR" returning 0 result(s)
01:07:05 INF: +RestClientCache::Lookup: cacheName="msopentechtest01.onmicrosoft.com", tag="PUBLISHING_LICENSES_UR"
01:07:05 INF: -RestClientCache::Lookup: cacheName="msopentechtest01.onmicrosoft.com", tag="PUBLISHING_LICENSES_UR" returning 0 result(s)
01:07:05 INF: +RestClientCache::Lookup: cacheName="msopentechtest01.onmicrosoft.com", tag="TEMPLATES_UR"
01:07:05 INF: -RestClientCache::Lookup: cacheName="msopentechtest01.onmicrosoft.com", tag="TEMPLATES_UR" returning 0 result(s)
01:07:05 INF: +RestClientCache::Lookup: cacheName="msopentechtest01.onmicrosoft.com", tag="CLOUD_DIAGNOSTICS_UR"
01:07:05 INF: -RestClientCache::Lookup: cacheName="msopentechtest01.onmicrosoft.com", tag="CLOUD_DIAGNOSTICS_UR" returning 0 result(s)
01:07:05 INF: +RestClientCache::Lookup: cacheName="msopentechtest01.onmicrosoft.com", tag="PERFORMANCE_UR"
01:07:05 INF: -RestClientCache::Lookup: cacheName="msopentechtest01.onmicrosoft.com", tag="PERFORMANCE_UR" returning 0 result(s)
01:07:05 INF: +RestClientCache::Lookup: cacheName="msopentechtest01.onmicrosoft.com", tag="DNS_CLIENT_RESULT"
01:07:05 INF: -RestClientCache::Lookup: cacheName="msopentechtest01.onmicrosoft.com", tag="DNS_CLIENT_RESULT" returning 0 result(s)
01:07:07 INF: ==> HttpClientQt::GET https://api.aadrm.com/my/v1/servicediscovery?email=chengzhang_lin@msopentechtest01.onmicrosoft.com
01:07:10 INF: Response StatusCode: 0
01:07:10 ERR: error: Unable to init SSL Context: 

rmsauth_010705-0729.log:
01:07:05 INF: FileCache: path: /home/administrator/.ms-ad/token_cache.dat

**Comment by munjaldoshi** [comment]
Kemmy, this also sounds like something you may be able to investigate and fix?

**Comment by Kammy6679** [comment]
@munjaldoshi , ???  We need your help to fix this issue ASAP. Because of this issue, we can't use any RMS feature in OpenSuse.

**Comment by Kammy6679** [comment]
We find that:
1. If build the RMS SDK on Ubuntu 14.04, and use this RMS SDK on OpenSuSe 13.2, will get "Server Error". But this RMS SDK can run normally on Ubuntu 14.04, 14.10, 15, RedHat 7.
2. If build the RMS SDK on OpenSuSe 13.2, it can run normally on OpenSuSe 13.2, but can't on the other OS(RedHat 6,7, Ubuntu 14,15).

I want to have an RMS SDK ,which can run normally on all OS(RedHat 6,7, Ubuntu 14,15, OpenSuse 12,13). 

PS: About whether need to build RMS SDK for each Linux OS, I have created issue #42, and already got the reply that it is not required to build RMS SDK for each Linux OS.

**Comment by AgentRX** [comment]
I've tested it on OpenSuSe with compiled library on Ubuntu.
The main problem is dependent libraries compatibility (in my case I had installed libopenssl-1.0.1 but library was compiled with libopenssl-1.0.0).

To get to known which libraries RMS dependent on please use the follow command:

```
ldd librms.so
```

then find if some libraries are missing or have incorrect versions and install them

**Comment by Kammy6679** [comment]
We can build the RMS SDK in OpenSuse 13.2,then use it in Ubuntu 14,Ubuntu 15, Red hat 7, OpenSuse 13.2.
