### ISSUE TITLE
get the value of PolicyDescriptor is NULL

### ISSUE THREAD

**Issue by Kammy6679** [AzureAD/rms-sdk-for-cpp#69]
1. Use the following code to encrypt the files
   static std::shared_ptr<UserPolicy>Create(
     PolicyDescriptor        & policyDescriptor,
     const std::string       & userId,
     IAuthenticationCallback & authenticationCallback,
     UserPolicyCreationOptions options);
2. When  decrypting, whether is owner, get the value of PolicyDescriptor is NULL.
   ![4](https://cloud.githubusercontent.com/assets/10860444/8983195/ba46d03e-36fa-11e5-8d7c-af9018851250.jpg)

**Comment by Kammy6679** [comment]
Ues the updated Active Directory Rights Management Services Mobile Device Extension(https://www.microsoft.com/download/details.aspx?id=43738), both of AAD RM and AD RMS  can reproduce this issue.

**Comment by Kammy6679** [comment]
If we can't get the value of PolicyDescriptor, it might cause the app can't display the relevant information in Restricted Access.
![123211111111111111](https://cloud.githubusercontent.com/assets/10860444/9138421/4a3c6fd0-3d56-11e5-8b6b-52f7e8967b84.png)

**Comment by Kammy6679** [comment]
After debugging, we found that:
Use "PolicyDescriptor" to encrypt the files. Then "UserPolicy->Type()"  is "TemplateBased",  not "Custom" when decrypting the files.

**Comment by AgentRX** [comment]
@Kammy6679, please checkout PR: https://github.com/AzureAD/rms-sdk-for-cpp/pull/75 and test it. Should work now.

**Comment by AgentRX** [comment]
@vladimp, Hello!

It seems there is an error in Windows SDK in:
**sdk/core/ProtectionPolicy.h**

```
93 bool IsAdhoc() const 
94    { 
95        return m_id.empty() || 
96               m_name.empty() ||
97               0 == _wcsicmp(L"00000000-0000-0000-0000-000000000000", m_id.c_str()); 
98    }
```

Both Template and AD-Hoc based methods returns ID and Name.
I've discovered that there is **"FromTemplate"** variable in response and now Linux SDK uses it to determine protection way was used.

**Comment by vladimp** [comment]
Yes, FromTemplate is the right way to do it..

Thanks,
Vladi.

**Comment by Kammy6679** [comment]
Thank you. It has been fixed.
