### ISSUE TITLE
there is no method to set "ConsentResult->accepted"

### ISSUE THREAD

**Issue by Kammy6679** [AzureAD/rms-sdk-for-cpp#77]
If user click "cancel ", how do we handle this?
![1234](https://cloud.githubusercontent.com/assets/10860444/9268033/3513b79a-428c-11e5-9051-6c45deadcbc3.jpg)

**Comment by AgentRX** [comment]
Done by PR: https://github.com/AzureAD/rms-sdk-for-cpp/pull/89
