### ISSUE TITLE
Get the different "ConsentList"

### ISSUE THREAD

**Issue by Kammy6679** [AzureAD/rms-sdk-for-cpp#78]
1. Call "GetTemplateList(const std::string　& userId,　 IAuthenticationCallback& authenticationCallback);"
2. Geting the URL value of "ConsentList" is “https://adrms.moblie.dev.foxitsoftware.cn/my/v1/enduserlicenses” when decrypting the PDF file. Please see the following screenshot.
   ![1234](https://cloud.githubusercontent.com/assets/10860444/9268127/6f651c3a-428d-11e5-9ef3-940e6b2bc452.jpg)
3. If does not call "GetTemplateList(const std::string　& userId,　 IAuthenticationCallback& authenticationCallback);", getting the URL value of "ConsentList" is ” https://adrms.moblie.dev.foxitsoftware.cn” when decrypting the PDF file. Please see the following screenshot.

![12312321](https://cloud.githubusercontent.com/assets/10860444/9268129/79766904-428d-11e5-9209-c3edd9fa61cd.png)

**Comment by AgentRX** [comment]
Closed due to #76
