### ISSUE TITLE
Get the wrong Content expiration

### ISSUE THREAD

**Issue by Kammy6679** [AzureAD/rms-sdk-for-cpp#80]
1. The content expiration time we set is : 2015-8-16　00:00:00
2. When decrypting this file, we use the following code to get this value, which is 2015-8-15　16:00:00 (8 hour difference)
   ![ctime](https://cloud.githubusercontent.com/assets/10860444/9276903/5145933c-42d9-11e5-9ba0-99a0c447fb4a.png)

PS: 
1. In Windows, the content expiration time got by MSICP is correct (2015-8-16　00:00:00).
2. Both of on-premis server and Azure server have this issue.

**Comment by AgentRX** [comment]
Fixed by PR: https://github.com/AzureAD/rms-sdk-for-cpp/pull/99
