### ISSUE TITLE
Calling "FileCachePtr = make_shared<FileCache>();" get the crash in Redhat 7

### ISSUE THREAD

**Issue by Kammy6679** [AzureAD/rms-sdk-for-cpp#85]
Here is a video for this issue: https://www.dropbox.com/s/pw22a7lfe9pn1q0/RMS.avi?dl=0

The reproduce steps:
1. In Redhat 7, download the demo from:https://www.dropbox.com/s/2umyz31suuk4fwe/Rms_Sample.setup.tar.gz?dl=0. 
PS: We used QT to package the RMS SDK sample 
1. unzip "Rms_Sample.setup.tar.gz", run "Rms_Sample.setup" to install the sample.
2. double click "Rms_sample.desktop" in your installation directory
3. Click "Encrypt PFLIE"
4. Choose a PDF file(test.pdf),  <b>the application crashes<\b>.
5. You can find a test.pdf.pfile( the file size is o bytes.)  in the same directory.
6. Open Terminal
7. Type "./rms_sample.sh" to run "Rms_sample"
8. Click "Encrypt PFLIE"
9. Choose a PDF file(test.pdf), enter the user name and psw, choose a template
10. Encrypt this file successfully

NOTE:
1. "Rms_sample.desktop"  just to run the script of "Rms_sample.sh", which is responsible for setting up environmental variables, and to run the executable program of "Rms_sample".
2. If write some logs when running  "Rms_sample", there is not this crash.
3. If use the command line to run the script of "Rms_sample.sh", there is not this crash.
4. Onle Red Hat 7 has this issue.

**Comment by Kammy6679** [comment]
@AgentRX ,using the latest RMS SDK(which adds an ability to turn logs off ), we can't reproduce this issue. So please close this issue

**Comment by prvijay** [comment]
Closing the issue
