### ISSUE TITLE
Add mechanism to cancel async operations

### ISSUE THREAD

**Issue by AgentRX** [AzureAD/rms-sdk-for-cpp#88]

**Comment by AgentRX** [comment]
@Kammy6679, to use this mechanism you should create:

```
auto cancelState = std::make_shared<std::atomic<bool>>(false);
```

then pass it as a last parametr to any Network operation of API:

```
- TemplateDescriptor::GetTemplateListAsync
- ProtectedFileStream::Acquire
- UserPolicy::Acquire
- UserPolicy::CreateFromTemplateDescriptor
- UserPolicy::Create
```

then if you want to cancel network operation just set it to true (from another thread):

```
cancelState->store(true);
```

The Network exception RMSNetworkException will be thrown with text: **"Network operation was cancelled by user"** and code **RMSNetworkException::CancelledByUser**

Also you can see it in example (during convert to PFILE using templates)

**Comment by Kammy6679** [comment]
Using the latest SDK, the last parametr of "GetTemplateListAsync" method is "std::launch              launchType". How to pass "auto cancelState = std::make_sharedstd::atomic<bool>(false);" as a last parametr to any Network operation of API?

**Comment by AgentRX** [comment]
@Kammy6679, I've merged it to dev branch now. Please try to use it again. If all is ok I'll create pull request to master

**Comment by Kammy6679** [comment]
@AgentRX , Can you please merged it to master branch? We can't use dev branch to verify this issue.

**Comment by AgentRX** [comment]
@Kammy6679 , I've merged. Please check it.
