### ISSUE TITLE
Does not install the certificate in Red hat 7, we get the crash when encrypting the file.

### ISSUE THREAD

**Issue by Kammy6679** [AzureAD/rms-sdk-for-cpp#90]
1. We <b>don't<\b> install the certificate in Red hat 7.(Red Hat Enterprise Linux Server release 7.0 (Maipo))
2. Run you sample
3. Use the ADFS/on-premise RMS server to encrypt the files, here is our setting:
    a) Client ID :  f3295a1c-bcfe-4430-80bf-1c0a5636e8e8
    b) Client Email:  tester01@mobile.dev.foxitsoftware.cn
    c) Redirect URI:  com.foxitsoftware.com.reader-for-linux://authorize
   ![123](https://cloud.githubusercontent.com/assets/10860444/9492279/b9f13924-4c28-11e5-8566-327e7eb9a374.png)
4. Click "Encrypt PFILE(template)", the sample is crash.

NOTE: from the log file(please see the below log)， we get the error“ ERR: QSslError: The issuer certificate of a locally looked up certificate could not be found”

rmsauth_184956-0826.log:
18:49:56 INF: FileCache: path: /home/lcz/.ms-ad/token_cache.dat

rms_log_184956-2608.log：
18:49:56 INF: +RestClientCache::Lookup: cacheName="mobile.dev.foxitsoftware.cn", tag="END_USER_LICENSES_UR"
18:49:56 INF: -RestClientCache::Lookup: cacheName="mobile.dev.foxitsoftware.cn", tag="END_USER_LICENSES_UR" returning 0 result(s)
18:49:56 INF: +RestClientCache::Lookup: cacheName="mobile.dev.foxitsoftware.cn", tag="PUBLISHING_LICENSES_UR"
18:49:56 INF: -RestClientCache::Lookup: cacheName="mobile.dev.foxitsoftware.cn", tag="PUBLISHING_LICENSES_UR" returning 0 result(s)
18:49:56 INF: +RestClientCache::Lookup: cacheName="mobile.dev.foxitsoftware.cn", tag="TEMPLATES_UR"
18:49:56 INF: -RestClientCache::Lookup: cacheName="mobile.dev.foxitsoftware.cn", tag="TEMPLATES_UR" returning 0 result(s)
18:49:56 INF: +RestClientCache::Lookup: cacheName="mobile.dev.foxitsoftware.cn", tag="CLOUD_DIAGNOSTICS_UR"
18:49:56 INF: -RestClientCache::Lookup: cacheName="mobile.dev.foxitsoftware.cn", tag="CLOUD_DIAGNOSTICS_UR" returning 0 result(s)
18:49:56 INF: +RestClientCache::Lookup: cacheName="mobile.dev.foxitsoftware.cn", tag="PERFORMANCE_UR"
18:49:56 INF: -RestClientCache::Lookup: cacheName="mobile.dev.foxitsoftware.cn", tag="PERFORMANCE_UR" returning 0 result(s)
18:49:56 INF: +RestClientCache::Lookup: cacheName="mobile.dev.foxitsoftware.cn", tag="DNS_CLIENT_RESULT"
18:49:56 INF: -RestClientCache::Lookup: cacheName="mobile.dev.foxitsoftware.cn", tag="DNS_CLIENT_RESULT" returning 0 result(s)
18:49:56 INF: ==> HttpClientQt::GET https://adrms.mobile.dev.foxitsoftware.cn/my/v1/servicediscovery?email=rms@mobile.dev.foxitsoftware.cn
18:49:57 ERR: QSslError: The issuer certificate of a locally looked up certificate could not be found

**Comment by AgentRX** [comment]
@Kammy6679 , I've just tested on CentOS Linux release 7.1.1503 and haven't got any crashes.
![snapshot1](https://cloud.githubusercontent.com/assets/10774820/9520427/2cbcc682-4c95-11e5-8677-9a49e276a375.png)

It seems that your samples weren't recompiled but rms library was. Could you recompile both of them and test again?

PS. If you copied libraries to /usr/lib please reinstall them to that location.

**Comment by Kammy6679** [comment]
@AgentRX , please try on Red hat 7. CentOS 7 can't reproduce this issue.

**Comment by AgentRX** [comment]
@Kammy6679, just have tested on RedHat. The same result:
![screenshot from 2015-08-31 02 53 57](https://cloud.githubusercontent.com/assets/10774820/9573527/a2cfbdb8-4f8b-11e5-9bd3-4af22c555019.png)

Have you compiled your samples and libraries on RedHat? Have you installed last updates on RedHat 7.0?
Please execute command **uname -r**. What the result?

My RedHat version now is 3.10.0-229.11.1.el7.x86_64

**Comment by Kammy6679** [comment]
We compiled sample and RMS SDK on open suse13.2, and then run the sample in Redhat.

**Comment by Kammy6679** [comment]
OpenSUSE 13.2
uname -r：3.16.6-2-desktop

red hat7
uname -r： 3.10.0-123.el7.x86_64
ldd rms_sample：
linux-vdso.so.1 =>  (0x00007fff1ddbc000)
 librmsauth.so => not found
 librmsauthWebAuthDialog.so => not found
 librms.so => not found
 librmscrypto.so => not found
 libQt5WebKitWidgets.so.5 => /home/lcz/FoxitSoftware/FoxitReader/lib/libQt5WebKitWidgets.so.5 (0x00007f662c3d8000)
 libQt5WebKit.so.5 => /home/lcz/FoxitSoftware/FoxitReader/lib/libQt5WebKit.so.5 (0x00007f6629e14000)
 libQt5XmlPatterns.so.5 => /home/lcz/FoxitSoftware/FoxitReader/lib/libQt5XmlPatterns.so.5 (0x00007f66297d3000)
 libQt5Widgets.so.5 => /home/lcz/FoxitSoftware/FoxitReader/lib/libQt5Widgets.so.5 (0x00007f6628f8f000)
 libQt5Network.so.5 => /home/lcz/FoxitSoftware/FoxitReader/lib/libQt5Network.so.5 (0x00007f6628c2b000)
 libQt5Xml.so.5 => /home/lcz/FoxitSoftware/FoxitReader/lib/libQt5Xml.so.5 (0x00007f66289ed000)
 libQt5Gui.so.5 => /home/lcz/FoxitSoftware/FoxitReader/lib/libQt5Gui.so.5 (0x00007f66282c7000)
 libQt5Core.so.5 => /home/lcz/FoxitSoftware/FoxitReader/lib/libQt5Core.so.5 (0x00007f6627b93000)
 libGL.so.1 => /lib64/libGL.so.1 (0x00007f662792c000)
 libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f662770f000)
 libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f6627408000)
 libm.so.6 => /lib64/libm.so.6 (0x00007f6627106000)
 libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f6626eef000)
 libc.so.6 => /lib64/libc.so.6 (0x00007f6626b2e000)
 libQt5OpenGL.so.5 => /home/lcz/FoxitSoftware/FoxitReader/lib/libQt5OpenGL.so.5 (0x00007f66268d4000)
 libQt5PrintSupport.so.5 => /home/lcz/FoxitSoftware/FoxitReader/lib/libQt5PrintSupport.so.5 (0x00007f662664c000)
 libQt5Sensors.so.5 => /home/lcz/FoxitSoftware/FoxitReader/lib/libQt5Sensors.so.5 (0x00007f662640c000)
 librt.so.1 => /lib64/librt.so.1 (0x00007f6626204000)
 libz.so.1 => /lib64/libz.so.1 (0x00007f6625fed000)
 libXrender.so.1 => /lib64/libXrender.so.1 (0x00007f6625de3000)
 libXcomposite.so.1 => /lib64/libXcomposite.so.1 (0x00007f6625be0000)
 libicui18n.so.52 => /home/lcz/FoxitSoftware/FoxitReader/lib/libicui18n.so.52 (0x00007f66257bf000)
 libicuuc.so.52 => /home/lcz/FoxitSoftware/FoxitReader/lib/libicuuc.so.52 (0x00007f6625437000)
 libX11.so.6 => /lib64/libX11.so.6 (0x00007f66250f9000)
 libxslt.so.1 => /lib64/libxslt.so.1 (0x00007f6624eb9000)
 libxml2.so.2 => /lib64/libxml2.so.2 (0x00007f6624b50000)
 libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f6624827000)
 libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x00007f66245d7000)
 libgstreamer-0.10.so.0 => /lib64/libgstreamer-0.10.so.0 (0x00007f66242ee000)
 libgstapp-0.10.so.0 => /lib64/libgstapp-0.10.so.0 (0x00007f66240e2000)
 libgstbase-0.10.so.0 => /lib64/libgstbase-0.10.so.0 (0x00007f6623e8d000)
 libgstinterfaces-0.10.so.0 => /lib64/libgstinterfaces-0.10.so.0 (0x00007f6623c7b000)
 libgstpbutils-0.10.so.0 => /lib64/libgstpbutils-0.10.so.0 (0x00007f6623a57000)
 libgstvideo-0.10.so.0 => /lib64/libgstvideo-0.10.so.0 (0x00007f6623839000)
 libQt5Quick.so.5 => /home/lcz/FoxitSoftware/FoxitReader/lib/libQt5Quick.so.5 (0x00007f6623284000)
 libQt5Qml.so.5 => /home/lcz/FoxitSoftware/FoxitReader/lib/libQt5Qml.so.5 (0x00007f6622c6f000)
 libQt5Sql.so.5 => /home/lcz/FoxitSoftware/FoxitReader/lib/libQt5Sql.so.5 (0x00007f6622a2d000)
 libQt5Positioning.so.5 => /home/lcz/FoxitSoftware/FoxitReader/lib/libQt5Positioning.so.5 (0x00007f66227ee000)
 libdl.so.2 => /lib64/libdl.so.2 (0x00007f66225e9000)
 libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x00007f66223e7000)
 /lib64/ld-linux-x86-64.so.2 (0x00007f662c632000)
 libglapi.so.0 => /lib64/libglapi.so.0 (0x00007f66221c1000)
 libXext.so.6 => /lib64/libXext.so.6 (0x00007f6621fae000)
 libXdamage.so.1 => /lib64/libXdamage.so.1 (0x00007f6621dab000)
 libXfixes.so.3 => /lib64/libXfixes.so.3 (0x00007f6621ba5000)
 libX11-xcb.so.1 => /lib64/libX11-xcb.so.1 (0x00007f66219a2000)
 libxcb-glx.so.0 => /lib64/libxcb-glx.so.0 (0x00007f6621788000)
 libxcb-dri2.so.0 => /lib64/libxcb-dri2.so.0 (0x00007f6621583000)
 libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f6621361000)
 libXxf86vm.so.1 => /lib64/libXxf86vm.so.1 (0x00007f662115b000)
 libdrm.so.2 => /lib64/libdrm.so.2 (0x00007f6620f4f000)
 libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f6620d29000)
 libicudata.so.52 => /home/lcz/FoxitSoftware/FoxitReader/lib/./libicudata.so.52 (0x00007f661f4be000)
 liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f661f298000)
 libffi.so.6 => /lib64/libffi.so.6 (0x00007f661f090000)
 libgmodule-2.0.so.0 => /lib64/libgmodule-2.0.so.0 (0x00007f661ee8b000)
 liborc-0.4.so.0 => /lib64/liborc-0.4.so.0 (0x00007f661ec08000)
 libXau.so.6 => /lib64/libXau.so.6 (0x00007f661ea03000)
 libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f661e7a2000)

**Comment by AgentRX** [comment]
@Kammy6679, could you share compiled libraries and samples?

**Comment by Kammy6679** [comment]
Redhat 7

ldd librms.so：
linux-vdso.so.1 =>  (0x00007fff7abfe000)
 librmscrypto.so => not found
 libssl.so.1.0.0 => /home/lcz/FoxitSoftware/FoxitReader/lib/libssl.so.1.0.0 (0x00007fd250463000)
 libcrypto.so.1.0.0 => /home/lcz/FoxitSoftware/FoxitReader/lib/libcrypto.so.1.0.0 (0x00007fd250040000)
 libQt5Widgets.so.5 => /home/lcz/FoxitSoftware/FoxitReader/lib/libQt5Widgets.so.5 (0x00007fd24f7fc000)
 libQt5XmlPatterns.so.5 => /home/lcz/FoxitSoftware/FoxitReader/lib/libQt5XmlPatterns.so.5 (0x00007fd24f1bb000)
 libQt5Gui.so.5 => /home/lcz/FoxitSoftware/FoxitReader/lib/libQt5Gui.so.5 (0x00007fd24ea96000)
 libQt5Network.so.5 => /home/lcz/FoxitSoftware/FoxitReader/lib/libQt5Network.so.5 (0x00007fd24e731000)
 libQt5Xml.so.5 => /home/lcz/FoxitSoftware/FoxitReader/lib/libQt5Xml.so.5 (0x00007fd24e4f3000)
 libQt5Core.so.5 => /home/lcz/FoxitSoftware/FoxitReader/lib/libQt5Core.so.5 (0x00007fd24ddbf000)
 libGL.so.1 => /lib64/libGL.so.1 (0x00007fd24db57000)
 libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fd24d93b000)
 libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fd24d634000)
 libm.so.6 => /lib64/libm.so.6 (0x00007fd24d331000)
 libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fd24d11b000)
 libc.so.6 => /lib64/libc.so.6 (0x00007fd24cd5a000)
 /lib64/ld-linux-x86-64.so.2 (0x00007fd2509cd000)
 libdl.so.2 => /lib64/libdl.so.2 (0x00007fd24cb55000)
 libz.so.1 => /lib64/libz.so.1 (0x00007fd24c93f000)
 libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x00007fd24c6f0000)
 libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007fd24c3c6000)
 libX11.so.6 => /lib64/libX11.so.6 (0x00007fd24c088000)
 libicui18n.so.52 => /home/lcz/FoxitSoftware/FoxitReader/lib/libicui18n.so.52 (0x00007fd24bc67000)
 libicuuc.so.52 => /home/lcz/FoxitSoftware/FoxitReader/lib/libicuuc.so.52 (0x00007fd24b8df000)
 libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x00007fd24b6dd000)
 librt.so.1 => /lib64/librt.so.1 (0x00007fd24b4d4000)
 libglapi.so.0 => /lib64/libglapi.so.0 (0x00007fd24b2ae000)
 libXext.so.6 => /lib64/libXext.so.6 (0x00007fd24b09c000)
 libXdamage.so.1 => /lib64/libXdamage.so.1 (0x00007fd24ae98000)
 libXfixes.so.3 => /lib64/libXfixes.so.3 (0x00007fd24ac92000)
 libX11-xcb.so.1 => /lib64/libX11-xcb.so.1 (0x00007fd24aa90000)
 libxcb-glx.so.0 => /lib64/libxcb-glx.so.0 (0x00007fd24a875000)
 libxcb-dri2.so.0 => /lib64/libxcb-dri2.so.0 (0x00007fd24a670000)
 libxcb.so.1 => /lib64/libxcb.so.1 (0x00007fd24a44f000)
 libXxf86vm.so.1 => /lib64/libXxf86vm.so.1 (0x00007fd24a248000)
 libdrm.so.2 => /lib64/libdrm.so.2 (0x00007fd24a03c000)
 libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fd249e17000)
 libffi.so.6 => /lib64/libffi.so.6 (0x00007fd249c0e000)
 libicudata.so.52 => /home/lcz/FoxitSoftware/FoxitReader/lib/./libicudata.so.52 (0x00007fd2483a3000)
 libXau.so.6 => /lib64/libXau.so.6 (0x00007fd24819e000)
 libpcre.so.1 => /lib64/libpcre.so.1 (0x00007fd247f3d000)
 liblzma.so.5 => /lib64/liblzma.so.5 (0x00007fd247d18000)

**Comment by Kammy6679** [comment]
Here is the compiled libraries and samples:
http://sync-us.foxitsoftware.com/pm/rms/temp/Rms_Sample1.setup.tar.gz

**Comment by AgentRX** [comment]
@Kammy6679 , thank you. Finally I could reproduce it on just installed Redhat 7.0.
The error text is:

```
GLib:ERROR:gmain.c:3061:g_main_dispatch: assertion failed: (current->dispatching_sources == &current_source_link)
```

On updated RedHat your samples work fine.
Now trying to get to know the root of crashing.

**Comment by prvijay** [comment]
As discussed with Foxit on 9/1, I am closing this issue as it does not repro on 7.0
